### ISSUE TITLE
Data Structure

### ISSUE THREAD

**Issue by bdbch** [redxtech/markit#26]
I guess we need to think about how our data will be structured.

#### So first some questions we should clarify:

- Do we use dexie/IndexDB or something else?
- How to authenticate?
- What will we use for our API?
- Who is responsible?
- How will collections be set together?

#### Decided notes

*[TBD]*

**Comment by redxtech** [comment]
Yeah I was thinking that we needed to discuss the data structure for the store.

We are using dexie though, and storing the store in a file in dropbox/google drive/s3. Using oauth or something.

**Comment by dreimer** [comment]
We could still be able to do it Backend-less so that its easier to host. Dropbox, Google Drive and S3 all offer JS Apis for direct uploading. Of course, that would make it harder to add other apadtors for Sftp or webdav for example. Another problem when going full Backend-less is the browser extension. It would then have to store the saved bookmarks and kind of inject them on page load.

**Comment by redxtech** [comment]
I think that something like this would be quite useful.
https://remotestorage.io/

**Comment by bdbch** [comment]
I think we already settled this with dexie and also basic implementation is already included. Closing this.
